use crate::{Result,abilities,arr,catalog,def,num,stats,str_field,tribe,truth};
use crate::combat::{Combat,Context,uid,keyword};
use serde_json::{Value,json};
impl Combat {
 pub fn trinket_event(&mut self,c:&Context,event:&str)->Result<()>{if c.depth>12{return Ok(());}let s=c.side;for (slot,id) in arr(&self.games[s]["season"]["trinkets"]).to_vec().iter().enumerate(){let id=id.as_str().ok_or("Invalid trinket")?;let rules=catalog().data["trinketRules"][id].clone();if !rules.is_array(){continue;}let key=format!("trinket:{slot}:{id}");if !self.games[s]["season"]["trinketData"].is_object(){self.games[s]["season"]["trinketData"]=json!({});}if !truth(&self.games[s]["season"]["trinketData"][&key]){let mut counts=vec![];let mut maximum=0;for t in arr(&catalog().data["tribes"]){let n=arr(&self.games[s]["board"]).iter().filter(|m|tribe(m,t.as_str().unwrap()).unwrap_or(false)).count();if n>maximum{maximum=n;counts.clear();}if n==maximum{counts.push(t.clone());}}let ty=if maximum>0{self.pick(&counts)}else{self.pick(&arr(&self.games[s]["season"]["tribes"]).to_vec())};let mut data=json!({"turn":self.games[s]["turn"]});if let Some(t)=ty{data["type"]=t;}self.games[s]["season"]["trinketData"][&key]=data;}for (index,rule) in arr(&rules).iter().enumerate(){if rule["event"]!=event{continue;}if let Some(t)=rule["subjectTribe"].as_str(){if c.event.as_deref().is_none_or(|id|!tribe(self.m(id),t).unwrap_or(false)){continue;}}let progress=format!("{key}:{index}{}",if truth(&rule["perTurn"]){format!(":{}",self.games[s]["turn"])}else{String::new()});let before=if truth(&rule["combatOnly"]){self.flags[s].get(&progress).copied().unwrap_or(0.)}else{self.count(s,&progress)};let amount=if event=="spend"&&truth(&rule["every"]){c.amount}else{1.};let after=before+amount;if truth(&rule["combatOnly"]){self.flags[s].insert(progress,after);}else{self.game_bump(s,&progress,amount);}let every=rule["every"].as_f64().unwrap_or(1.);let limit=rule["limit"].as_f64().unwrap_or(f64::INFINITY);let triggers=(after.min(limit)/every).floor()-(before.min(limit)/every).floor();for _ in 0..triggers as usize{let next=Context{depth:c.depth+1,..c.clone()};if rule["op"]=="trinketCustom"{self.trinket_custom(&next,id,event,&key)?;}else if rule["op"]=="trinketDraw"{self.recruit(s,|r|{let tier=num(&r.state["tier"]);if let Some(m)=r.draw(|d|num(&d["tier"])<=tier&&(rule["key"].is_null()||arr(&d["mechanics"]).contains(&rule["key"])))?{r.trinket_card(m)?;}Ok(())})?;}else{let m=self.make("s14_BG20_GEM",false)?;let id=uid(&m);self.cards.insert(id.clone(),m);self.effect(&next,&id,rule)?;}}}}Ok(())}
 fn ends(&self,s:usize,t:Option<&str>)->Vec<String>{let ids:Vec<_>=self.boards[s].iter().filter(|id|t.is_none_or(|t|tribe(self.m(id),t).unwrap_or(false))).cloned().collect();let mut out=vec![];if let Some(x)=ids.first(){out.push(x.clone());}if ids.len()>1{out.push(ids.last().unwrap().clone());}out}
 fn extra(&mut self,id:&str,a:Value){if !self.m(id)["extraAbilities"].is_array(){self.mm(id)["extraAbilities"]=json!([]);}self.mm(id)["extraAbilities"].as_array_mut().unwrap().push(a);}
 pub fn trinket_custom(&mut self,c:&Context,id:&str,event:&str,key:&str)->Result<()>{let s=c.side;match id {
 "BG30_MagicItem_301"=>{for x in self.boards[s].clone(){if self.m(&x)["id"]=="s14_BG25_008"{keyword(self.mm(&x),"嘲讽");keyword(self.mm(&x),"复生");}}},
 "BG30_MagicItem_303"=>{let m=self.make("s14_BG_TTN_401",false)?;let m=stats::global(&self.games[s],m)?;self.pending[s].push(m);},
 "BG30_MagicItem_310"=>{for x in self.boards[s].clone(){if self.m(&x)["id"]=="s14_BG25_354"{self.gain(c,None,&x,0.,num(&self.m(&x)["health"]))?;}}},
 "BG30_MagicItem_403"=>{for x in self.boards[s].clone(){if !arr(&catalog().data["tribes"]).iter().any(|t|tribe(self.m(&x),t.as_str().unwrap()).unwrap_or(false)){self.gain(c,None,&x,2.*num(&self.m(&x)["attack"]),2.*num(&self.m(&x)["health"]))?;}}},
 "BG30_MagicItem_411"|"BG30_MagicItem_917"=>{for x in self.boards[s].clone(){if tribe(self.m(&x),if id=="BG30_MagicItem_411"{"野猪人"}else{"纳迦"})?{let a=if id=="BG30_MagicItem_411"{json!({"event":"death","op":"generate","id":"BG20_GEM","amount":2,"trinket":true})}else{json!({"event":"death","op":"randomSpellcraft","trinket":true})};self.extra(&x,a);}}},
 "BG30_MagicItem_442"=>{if let Some(subject)=&c.event{let m=self.m(subject).clone();if truth(&m["gems"]){let mut card=self.make("s14_BG30_MagicItem_442t",false)?;card["attack"]=m["gems"]["attack"].clone();card["health"]=m["gems"]["health"].clone();self.summon_ctx(c,card,c.pos.unwrap_or(self.boards[s].len()))?;}}},
 "BG30_MagicItem_902"|"BG32_MagicItem_360"=>{for x in self.ends(s,if id=="BG32_MagicItem_360"{Some("亡灵")}else{None}){keyword(self.mm(&x),if id=="BG32_MagicItem_360"{"复生"}else{"圣盾"});}},
 "BG30_MagicItem_924"|"BG30_MagicItem_924t"|"BG30_MagicItem_952"=>{let mut ids:Vec<_>=self.boards[s].iter().filter(|x|tribe(self.m(x),if id=="BG30_MagicItem_952"{"元素"}else{"海盗"}).unwrap_or(false)).cloned().collect();self.shuffle(&mut ids);for x in ids.into_iter().take(2){if id=="BG30_MagicItem_952"{self.extra(&x,json!({"event":"death","op":"summon","id":"BG26_537","noScale":true}));}else{let n=if id.ends_with('t'){6.}else{3.};self.gain(c,None,&x,n,n)?;}}},
 "BG30_MagicItem_962"=>{let mut b=self.board(s);b.sort_by(|a,b|num(&a["attack"]).total_cmp(&num(&b["attack"])));for m in b.iter().take(2){self.gain(c,None,&uid(m),num(&m["attack"]),num(&m["health"]))?;}},
 "BG30_MagicItem_995"=>{for x in self.boards[s].clone(){self.gain(c,None,&x,0.,(num(&self.m(&x)["attack"])/2.).ceil())?;}},
 "BG32_MagicItem_200"=>{if let Some(t)=&c.event{if tribe(self.m(t),"野兽")?{let n=2.+self.game_bump(s,&format!("{key}:growth"),1.);self.gain(c,None,t,n,0.)?;}}},
 "BG32_MagicItem_278"=>{if let Some(t)=&c.event{let mut card=self.make("s14_BG31_171t",false)?;card["attack"]=self.m(t)["attack"].clone();card["health"]=self.m(t)["health"].clone();self.recruit(s,|r|r.trinket_card(card))?;}},
 "BG32_MagicItem_306"=>{for x in self.boards[s].clone(){if abilities(self.m(&x))?.iter().any(|a|a["event"]=="death"){self.death(c,&x)?;}}},
 "BG32_MagicItem_860"|"BG32_MagicItem_860t"=>{for _ in 0..if id.ends_with('t'){2}else{1}{let m=self.make("s14_BG28_603t",false)?;let mut m=stats::global(&self.games[s],m)?;keyword(&mut m,"嘲讽");self.summon_ctx(c,m,c.pos.unwrap_or(self.boards[s].len()))?;}},
 "BG32_MagicItem_922"=>{if event=="spell"{self.game_bump(s,&format!("{key}:growth"),1.);}else if let Some(t)=self.boards[s].first().cloned(){let n=3.+self.count(s,&format!("{key}:growth"));self.gain(c,None,&t,n,n)?;}},
 "BG35_MagicItem_701"=>{let growth=format!("{key}:growth");let aura=format!("{key}:aura");if event=="combat"{let n=1.+self.count(s,&growth);self.flags[s].insert(aura,n);for x in self.boards[s].clone(){if tribe(self.m(&x),"野兽")?{self.gain(c,None,&x,n,n)?;}}}else if let Some(t)=&c.event{if tribe(self.m(t),"野兽")?{let n=self.flags[s].get(&aura).copied().unwrap_or(0.);if n!=0.{self.gain(c,None,t,n,n)?;}self.game_bump(s,&growth,1.);}}},
 "BG35_MagicItem_732"=>{if event=="combat"{let ids:Vec<_>=self.boards[s].iter().take(3).cloned().collect();let mut stored=vec![];for id in ids{stored.push(self.copy(&self.m(&id).clone())?);self.mm(&id)["health"]=json!(0);}self.games[s]["season"]["trinketData"][key]["stored"]=json!(stored);}else if self.boards[s].is_empty(){let cards=arr(&self.games[s]["season"]["trinketData"][key]["stored"]).to_vec();if !cards.is_empty(){self.games[s]["season"]["trinketData"][key]["stored"]=json!([]);for card in cards{let card=self.copy(&card)?;self.summon_ctx(c,card,self.boards[s].len())?;}}}},
 "BG35_MagicItem_740"=>{for x in self.boards[s].clone(){self.extra(&x,json!({"event":"death","op":"buff","target":"all","attack":2,"health":2,"permanent":true,"noScale":true}));}},
 "BG35_MagicItem_752"=>{for x in self.ends(s,None){self.battlecry(&Context{target:None,..c.clone()},&x)?;}},
 "BG35_MagicItem_754"=>{let n=arr(&self.games[s]["hand"]).iter().filter(|m|def(m["id"].as_str().unwrap()).unwrap()["kind"]!="spell").map(|m|num(&m["attack"])).fold(0.,f64::max);for x in self.boards[s].clone(){if tribe(self.m(&x),"鱼人")?{self.gain(c,None,&x,n,0.)?;}}},
 "BG35_MagicItem_923"=>{for x in self.boards[s].clone(){self.gain(c,None,&x,2.,2.)?;self.permanent(s,&x,2.,2.);}},
 "BG36_MagicItem_404"|"BG36_MagicItem_404t"=>{let n=if id.ends_with('t'){10.}else{4.};self.deity(s,n,n);},
 "BG36_MagicItem_600"=>{for x in self.boards[s].clone(){if self.m(&x)["id"]=="s14_BG36_318"{keyword(self.mm(&x),"复生");}}},
 "BG36_MagicItem_450"=>{if let Some(t)=&c.event{if self.m(t)["id"]=="s14_BG36_205"{let n=4.*self.game_bump(s,&format!("{key}:bait"),1.);for x in self.boards[s].clone(){if tribe(self.m(&x),"野兽")?{self.gain(c,None,&x,n,n)?;}}}}},
 _=>return Err(format!("RUST_COMBAT_TRINKET_INCOMPLETE: {id} {event}"))
 }Ok(())}
}
