use crate::{Result,abilities,arr,catalog,def,has,num,primitives,stats,str_field,tribe,truth};
use crate::combat::{Combat,Context,bump,mc,uid,kw,keyword};
use serde_json::{Value,json};
impl Combat {
 pub fn targets(&mut self,c:&Context,id:&str,a:&Value)->Result<Vec<String>>{let board=self.boards[c.side].clone();let target=a["target"].as_str().unwrap_or("self");let mut ts=match target{"self"=>vec![id.to_owned()],"event"=>c.event.clone().into_iter().collect(),"selected"=>c.target.clone().into_iter().collect(),"all"|"left"=>board.clone(),"others"|"random"|"randomFour"=>board.iter().filter(|x|*x!=id).cloned().collect(),"adjacent"=>board.iter().position(|x|x==id).map(|i|[i.checked_sub(1),Some(i+1)].into_iter().flatten().filter_map(|i|board.get(i).cloned()).collect()).unwrap_or_default(),"golden"=>board.iter().filter(|x|truth(&self.m(x)["golden"])).cloned().collect(),"shielded"=>board.iter().filter(|x|kw(self.m(x),"圣盾")).cloned().collect(),"menagerie"=>{let mut ts=vec![];for t in arr(&catalog().data["tribes"]){let candidates:Vec<_>=board.iter().filter(|x|!ts.contains(x)&&tribe(self.m(x),t.as_str().unwrap()).unwrap_or(false)).cloned().collect();if let Some(x)=self.pick(&candidates){ts.push(x);}}ts},"boardAndHand"|"handLeft"|"randomHand"|"shop"=>{let zone=if target=="shop"{"shop"}else{"hand"};let cards:Vec<_>=arr(&self.games[c.side][zone]).iter().filter(|m|def(m["id"].as_str().unwrap()).unwrap()["kind"]!="spell"||target=="shop").cloned().collect();let mut ids=vec![];for m in cards{let id=uid(&m);self.cards.entry(id.clone()).or_insert(m);ids.push(id);}if target=="boardAndHand"{let mut all=board.clone();all.extend(ids);all}else if target=="handLeft"{ids.truncate(1);ids}else if target=="randomHand"{self.shuffle(&mut ids);ids.truncate(1);ids}else{ids}},_=>vec![]};if let Some(t)=a["tribe"].as_str(){ts.retain(|x|tribe(self.m(x),t).unwrap_or(false));}if target=="random"||target=="randomFour"{self.shuffle(&mut ts);ts.truncate(if target=="random"{1}else{4});}if target=="left"{ts.truncate(1);}Ok(ts)}
 pub fn gain(&mut self,c:&Context,source:Option<&str>,id:&str,mut a:f64,mut h:f64)->Result<()>{if c.depth>20{return Ok(());}if let Some(src)=source{if def(str_field(self.m(src),"id")?)?["kind"]!="spell"&&tribe(self.m(src),"元素")?&&(a>0.||h>0.){let bonus=self.trinket(c.side,"380")*(1.+(self.count(c.side,"trinketElementals")/5.).floor())+self.boards[c.side].iter().filter(|x|has(self.m(x),"elementalGrantAura").unwrap_or(false)).map(|x|if truth(&self.m(x)["golden"]){6.}else{3.}).sum::<f64>();a+=bonus;h+=bonus;}}if tribe(self.m(id),"元素")?{a+=num(&self.games[c.side]["season"]["buffs"]["elementalGrant"]["attack"]);h+=num(&self.games[c.side]["season"]["buffs"]["elementalGrant"]["health"]);}self.add(id,a,h);let on=self.boards[c.side].iter().any(|x|x==id);if on&&a>0.{for src in self.boards[c.side].clone(){if has(self.m(&src),"healthOnAttackGain")?{self.add(id,0.,if truth(&self.m(&src)["golden"]){6.}else{3.});}}}if on&&has(self.m(id),"handEchoStats")?{let cards:Vec<_>=arr(&self.games[c.side]["hand"]).iter().filter(|x|def(x["id"].as_str().unwrap()).unwrap()["kind"]!="spell").take(2).cloned().collect();let f=if truth(&self.m(id)["golden"]){2.}else{1.};for m in cards{let hand=uid(&m);self.cards.entry(hand.clone()).or_insert(m);self.gain(&Context{depth:c.depth+1,..c.clone()},None,&hand,a*f,h*f)?;}}let mut state=self.games[c.side].clone();state["board"]=json!(self.board(c.side));let next=stats::sync(&state,self.m(id).clone(),on)?;self.cards.insert(id.to_owned(),next);if !on{let v=self.m(id).clone();for zone in ["hand","shop"]{if let Some(m)=self.games[c.side][zone].as_array_mut().unwrap().iter_mut().find(|m|m["uid"]==id){*m=v.clone();}}}if source==Some(id){let cid=self.m(id)["id"].as_str().unwrap().to_owned();let i=self.boards[c.side].iter().position(|x|x==id);if let Some(i)=i{let indices=if self.item(c.side,"BG35_MagicItem_156")>0.&&cid=="s14_BG34_500"{vec![i.checked_sub(1),Some(i+1)]}else if self.item(c.side,"BG35_MagicItem_924")>0.&&cid=="s14_BG31_035"{vec![i.checked_sub(1)]}else{vec![]};for j in indices.into_iter().flatten(){if let Some(x)=self.boards[c.side].get(j).cloned(){self.gain(&Context{depth:c.depth+1,..c.clone()},None,&x,a,h)?;}}}}if self.m(id)["id"]=="s14_TB_BaconShop_HP_033t"{for x in self.boards[c.side].clone(){if self.m(&x)["id"]=="s14_TB_BaconShop_HERO_33_Buddy"{let f=if truth(&self.m(&x)["golden"]){2.}else{1.};self.gain(&Context{depth:c.depth+1,..c.clone()},None,&x,a*f,h*f)?;}}}Ok(())}
 pub fn scale(&mut self,s:usize,key:&str,a:f64,h:f64)->Result<()>{self.recruit(s,|r|r.scale(key,a,h))?;if ["beast","undead","beastCombat"].contains(&key){for id in self.boards[s].clone(){if tribe(self.m(&id),if key=="undead"{"亡灵"}else{"野兽"})?{self.add(&id,a,h);}}}Ok(())}
 pub fn deity(&mut self,s:usize,a:f64,h:f64){if !truth(&self.games[s]["season"]["deity"]){return;}for (k,n) in [("attack",a),("health",h)]{self.games[s]["season"]["deity"][k]=json!(num(&self.games[s]["season"]["deity"][k])+n);}for id in self.boards[s].clone(){if mc(self.m(&id),"awakenedDeity")!=0.{self.add(&id,a,h);}}}
 pub fn run(&mut self,c:&Context,id:&str,event:&str)->Result<()>{if c.depth>12{return Ok(());}let repeats=if event=="rally"{self.boards[c.side].iter().filter(|x|has(self.m(x),"repeatAllTriggers").unwrap_or(false)).map(|x|if truth(&self.m(x)["golden"]){3}else{2}).max().unwrap_or(1)}else{1};for _ in 0..repeats{for a in abilities(self.m(id))?.into_iter().filter(|a|a["event"]==event){self.effect(&Context{depth:c.depth+1,..c.clone()},id,&a)?;}}Ok(())}
 pub fn battlecry(&mut self,c:&Context,id:&str)->Result<()>{let mut c=c.clone();let abilities=abilities(self.m(id))?;if c.target.is_none(){if let Some(a)=abilities.iter().find(|a|a["event"]=="battlecry"&&a["target"]=="selected"){let ts:Vec<_>=self.boards[c.side].iter().filter(|x|*x!=id&&a["tribe"].as_str().is_none_or(|t|tribe(self.m(x),t).unwrap_or(false))).cloned().collect();c.target=self.pick(&ts);}}let mut n=self.boards[c.side].iter().filter(|x|*x!=id&&(has(self.m(x),"brann").unwrap_or(false)||has(self.m(x),"repeatAllTriggers").unwrap_or(false))).map(|x|if truth(&self.m(x)["golden"]){3}else{2}).max().unwrap_or(1);if tribe(self.m(id),"龙")?{n+=self.trinket(c.side,"215") as usize;}let key=format!("warDrum:{}",self.games[c.side]["turn"]);let actual=abilities.iter().any(|a|a["event"]=="battlecry");if actual&&self.game_bump(c.side,&key,1.)==1.{n+=2*self.item(c.side,"BG32_MagicItem_416") as usize;}n+=self.count(c.side,&format!("prizeBattlecry:{}",self.games[c.side]["turn"])) as usize;for _ in 0..n{self.run(&c,id,"battlecry")?;if actual{self.games[c.side]["season"]["battlecries"]=json!(num(&self.games[c.side]["season"]["battlecries"])+1.);for x in self.boards[c.side].clone(){self.run(&Context{event:Some(id.to_owned()),..c.clone()},&x,"battlecryTriggered")?;}let n=self.trinket(c.side,"203");if n>0.{let mut ends=vec![];if let Some(x)=self.boards[c.side].first(){ends.push(x.clone());}if let Some(x)=self.boards[c.side].last(){if !ends.contains(x){ends.push(x.clone());}}for x in ends{self.add(&x,5.*n,5.*n);}}}}Ok(())}
 pub fn gift(&mut self,c:&Context,id:&str,event:&str)->Result<()>{let gift=self.m(id)["gift"].as_str().unwrap_or("").strip_prefix("BG36_MidGameEffect_000t").unwrap_or("").to_owned();match (event,gift.as_str()) {("combat","89")=>{let d=&self.games[c.side]["season"]["deity"];if truth(d){self.add(id,num(&d["attack"]),num(&d["health"]));}},("combat","90")=>{let m=self.copy(&self.m(id).clone())?;let p=self.boards[c.side].iter().position(|x|x==id).unwrap()+1;self.summon_ctx(c,m,p)?;},("combat","7")=>self.add(id,0.,num(&self.m(id)["health"])),("combat","71")=>self.add(id,num(&self.m(id)["attack"]),0.),("combat","16")=>self.death(c,id)?,("rally","80")=>self.effect(c,id,&json!({"event":"rally","op":"spell","id":"BG20_GEM","amount":2}))?,("death","52")=>{self.games[c.side]["season"]["freeRefresh"]=json!(num(&self.games[c.side]["season"]["freeRefresh"])+2.);},("death","5")=>{self.recruit(c.side,|r|{if let Some(m)=r.draw_spell(|_|true)?{r.put_hand(m,true)?;}Ok(())})?;},_=>{}}Ok(())}
 pub fn effect(&mut self,c:&Context,id:&str,a:&Value)->Result<()>{let m=self.m(id).clone();let f=if truth(&m["golden"])&&!truth(&a["noScale"]){2.}else{1.};let n=a["amount"].as_f64().unwrap_or(1.)*f;let op=a["op"].as_str().unwrap_or("");match op {
 "buff"|"deathStats"|"gem"|"spellProgressBuff"|"goldHealth"|"morglton"|"satellite"=>{let (attack,health)=match op{"deathStats"=>(num(&m["attack"]),mc(&m,"deathStatsHealth")),"gem"=>((1.+num(&self.games[c.side]["season"]["buffs"]["gem"]["attack"]))*n,(1.+num(&self.games[c.side]["season"]["buffs"]["gem"]["health"]))*n),"spellProgressBuff"=>{let p=(self.count(c.side,"allSpells")/3.).floor();((num(&a["attack"])+p)*f,(num(&a["health"])+p)*f)},"goldHealth"=>(0.,(1.+num(&self.games[c.side]["season"]["goldSpentTurn"]))*f),"morglton"=>{let v=(3.+self.count(c.side,"morglton"))*f;(if truth(&a["attack"]){v}else{0.},if truth(&a["health"]){v}else{0.})},_=>(num(&a["attack"])*f,num(&a["health"])*f)};for x in self.targets(c,id,a)?{self.gain(c,Some(id),&x,attack,health)?;if let Some(k)=a["keyword"].as_str(){if truth(&a["toggle"])&&kw(self.m(&x),k){self.mm(&x)["keywords"].as_array_mut().unwrap().retain(|v|v!=k);}else{keyword(self.mm(&x),k);}}if a["key"]=="nagaWindfury"&&tribe(self.m(&x),"纳迦")?{keyword(self.mm(&x),"风怒");}if truth(&a["permanent"]){self.permanent(c.side,&x,attack,health);}if op=="gem"{let ga=num(&self.m(&x)["gems"]["attack"])+attack;let gh=num(&self.m(&x)["gems"]["health"])+health;self.mm(&x)["gems"]=json!({"attack":ga,"health":gh});for _ in 0..n as usize{self.run(&Context{event:Some(id.to_owned()),..c.clone()},&x,"gemPlayed")?;}}if op=="satellite"{self.mm(&x)["magneticCount"]=json!(num(&self.m(&x)["magneticCount"])+1.);}}},
 "setStats"=>{for x in self.targets(c,id,a)?{self.mm(&x)["attack"]=json!(num(&a["attack"]));self.mm(&x)["health"]=json!(if truth(&a["health"]){num(&a["health"])}else{1.});}},
 "doubleAttack"=>{for x in self.targets(c,id,a)?{self.add(&x,num(&self.m(&x)["attack"])*f,0.);}},
 "scale"=>self.scale(c.side,str_field(a,"key")?,num(&a["attack"])*f,num(&a["health"])*f)?,
 "summon"=>{let count=if truth(&m["golden"])&&!truth(&a["noScale"]){a["goldenAmount"].as_u64().or(a["amount"].as_u64()).unwrap_or(1)}else{a["amount"].as_u64().unwrap_or(1)};let golden=a["summonGolden"].as_bool().unwrap_or(truth(&m["golden"])&&!truth(&a["noScale"]));for i in 0..count{let card=self.make(&format!("s14_{}",str_field(a,"id")?),golden)?;let mut card=stats::global(&self.games[c.side],card)?;if tribe(&card,"野兽")?{stats::add(&mut card,num(&self.games[c.side]["season"]["buffs"]["beastCombat"]["attack"]),num(&self.games[c.side]["season"]["buffs"]["beastCombat"]["health"]));}let p=c.pos.or_else(||self.boards[c.side].iter().position(|x|x==id)).map(|p|p+1).unwrap_or(0)+i as usize;self.summon_ctx(c,card,p)?;}},
 "rally"=>{if let Some(t)=&c.target{for _ in 0..n as usize{self.run(c,t,"rally")?;}}},"battlecry"=>{for x in self.targets(c,id,a)?{self.battlecry(&Context{target:None,..c.clone()},&x)?;}},"deathrattle"=>{if let Some(t)=&c.target{for _ in 0..n as usize{self.death(c,t)?;}}},
 "damageAll"=>{let mut ids=self.boards[c.side].clone();ids.extend(self.boards[1-c.side].clone());for x in ids{if x!=id{self.damage(&x,n,Some(id))?;}}},
 "handStats"=>{for card in arr(&self.games[c.side]["hand"]).to_vec(){if def(str_field(&card,"id")?)?["kind"]!="spell"{self.add(id,num(&card["attack"])*f,num(&card["health"])*f);}}},
 "handAttack"=>{let value=arr(&self.games[c.side]["hand"]).iter().filter(|m|def(m["id"].as_str().unwrap()).unwrap()["kind"]!="spell").map(|m|num(&m["attack"])).fold(0.,f64::max);self.gain(c,Some(id),id,value*f,0.)?;},
 "targetAttack"=>{if let Some(t)=&c.target{self.gain(c,Some(id),id,num(&self.m(t)["attack"])*f,0.)?;}},
 "salvage"=>{let i=self.boards[c.side].iter().position(|x|x==id).unwrap_or(0);let neighbors:Vec<_>=[i.checked_sub(1),if f==2.{Some(i+1)}else{None}].into_iter().flatten().filter_map(|j|self.boards[c.side].get(j).cloned()).filter(|x|self.m(x)["id"]!=m["id"]).collect();let mut stored=vec![];for x in neighbors{stored.push(self.copy(&self.m(&x).clone())?);self.mm(&x)["health"]=json!(0);}self.mm(id)["storedMinions"]=json!(stored);},
 "salvageSummon"=>{for card in arr(&m["storedMinions"]){let copy=self.copy(card)?;self.summon_ctx(c,copy,c.pos.unwrap_or(self.boards[c.side].len()))?;}},
 "kodoStats"=>{if let Some(t)=&c.event{if bump(self.mm(id),"kodoSummons",1.)<=3.{self.gain(c,Some(id),t,num(&m["attack"])*f,m["counters"]["deathStatsHealth"].as_f64().unwrap_or(num(&m["health"]))*f)?;}}},
 "stoneSlab"=>{if let Some(t)=&c.event{let turn=num(&self.games[c.side]["turn"]);if mc(&m,"stoneSlabTurn")!=turn{bump(self.mm(id),"stoneSlabTurn",turn-mc(&m,"stoneSlabTurn"));self.gain(c,Some(id),t,20.,20.)?;self.gain(c,Some(id),t,num(&self.m(t)["attack"])*f,num(&self.m(t)["health"])*f)?;}}},
 "ravager"=>{if let Some(t)=&c.target{let enemy=self.boards[1-c.side].clone();let i=enemy.iter().position(|x|x==t).unwrap();let adjacent:Vec<_>=[i.checked_sub(1),Some(i+1)].into_iter().flatten().filter_map(|j|enemy.get(j).cloned()).collect();let victims=if f==2.{adjacent}else{self.pick(&adjacent).into_iter().collect()};self.damage(t,num(&m["attack"]),Some(id))?;for x in victims{self.damage(&x,num(&m["attack"]),Some(id))?;}}},
 "jailbird"=>{if let Some(t)=&c.target{if self.boards[c.side].len()<7{let mut golem=self.make("s14_BG30_MagicItem_442t",false)?;golem["attack"]=json!(num(&m["attack"])*f);golem["health"]=json!(num(&m["health"])*f);let gid=uid(&golem);let damage=num(&self.m(t)["attack"]);let p=self.boards[c.side].iter().position(|x|x==id).unwrap_or(0)+1;self.summon_ctx(c,golem,p)?;self.damage(t,num(&self.m(&gid)["attack"]),Some(&gid))?;self.damage(&gid,damage,Some(t))?;}}},
 "randomBeastSix"=>{let cards:Vec<_>=arr(&catalog().data["minionPool"]).iter().filter_map(|id|def(id.as_str().unwrap()).ok()).filter(|d|self.games[c.side]["pool"].get(d["id"].as_str().unwrap()).is_some()&&(arr(&d["races"]).iter().any(|x|x=="野兽")||d["tribe"]=="全部")).cloned().collect();if let Some(d)=self.pick(&cards){let mut card=self.make(str_field(&d,"id")?,false)?;card["attack"]=json!(6.*f);card["health"]=json!(6.*f);self.summon_ctx(c,card,c.pos.unwrap_or(self.boards[c.side].len()))?;}},
 "summonHand"|"pendingHandMurloc"=>{let mut cards:Vec<_>=arr(&self.games[c.side]["hand"]).iter().filter(|x|def(x["id"].as_str().unwrap()).unwrap()["kind"]!="spell"&&(op!="pendingHandMurloc"||tribe(x,"鱼人").unwrap_or(false))&&num(&x["lockedUntil"])<=num(&self.games[c.side]["turn"])&&num(&x["lockedTier"])<=num(&self.games[c.side]["tier"])).cloned().collect();cards.sort_by(|a,b|num(&b["attack"]).total_cmp(&num(&a["attack"])));for (i,card) in cards.iter().take(f as usize).enumerate(){let copy=self.copy(card)?;if op=="pendingHandMurloc"{self.pending[c.side].push(copy);}else{let p=c.pos.or_else(||self.boards[c.side].iter().position(|x|x==id)).map(|p|p+1).unwrap_or(0)+i;self.summon_ctx(c,copy,p)?;}}},
 "summonSelfCopy"=>{if arr(&self.games[c.side]["hand"]).iter().any(|m|m["uid"]==id){let mut copy=self.copy(&m)?;copy["attack"]=json!(num(&copy["attack"])*f);copy["health"]=json!(num(&copy["health"])*f);self.summon_ctx(c,copy,self.boards[c.side].len())?;}},
 "summonRemembered"=>{for remembered in arr(&m["remembered"]){if let Some(card)=arr(&self.games[c.side]["hand"]).iter().find(|m|m["uid"]==*remembered).cloned(){let mut copy=card.clone();copy["uid"]=self.make(str_field(&card,"id")?,false)?["uid"].clone();copy["copies"]=json!({});self.summon_ctx(c,copy,c.pos.unwrap_or(self.boards[c.side].len()))?;}}},
 "kangor"=>{for dead in self.dead_mechs[c.side].clone().iter().take(2*f as usize){let card=self.make(str_field(dead,"id")?,truth(&dead["golden"]))?;let card=stats::global(&self.games[c.side],card)?;self.summon_ctx(c,card,c.pos.unwrap_or(self.boards[c.side].len()))?;}},
 "growingBeast"=>{if let Some(t)=&c.event{self.gain(c,Some(id),t,3.*f+mc(&m,"beastGrowth"),0.)?;bump(self.mm(id),"beastGrowth",f);self.remember(c.side,id,"beastGrowth",f);}},
 "parrotGold"=>{if mc(&m,"parrotDamage")<35.&&c.amount>0.{let total=bump(self.mm(id),"parrotDamage",c.amount);self.remember(c.side,id,"parrotDamage",c.amount);if total>=35.{for _ in 0..f as usize{let card=self.make("s14_BG28_830",false)?;self.recruit(c.side,|r|r.put_hand(card,true))?;}}}},
 "stripDefenses"=>{if let Some(t)=&c.target{self.mm(t)["keywords"].as_array_mut().unwrap().retain(|k|k!="嘲讽"&&k!="复生");}},"killKiller"=>{if let Some(t)=&c.killer{if self.boards[1-c.side].contains(t){self.mm(t)["health"]=json!(0);}}},
 "shieldReborn"=>{if let Some(t)=&c.event{keyword(self.mm(t),"圣盾");self.gain(c,Some(id),id,7.*f,7.*f)?;}},
 "inheritReborn"=>{if let Some(t)=&c.event{if let Some(x)=self.boards[c.side].iter().rev().find(|x|tribe(self.m(x),"亡灵").unwrap_or(false)).cloned(){let n=num(&self.m(t)["attack"])*f;self.gain(c,Some(id),&x,n,n)?;}}},
 "rallyDeathrattle"=>{if let Some(t)=&c.event{if abilities(self.m(t))?.iter().any(|a|a["event"]=="rally"){if let Some(x)=self.boards[c.side].iter().find(|x|num(&self.m(x)["health"])>0.&&abilities(self.m(x)).unwrap().iter().any(|a|a["event"]=="death")).cloned(){for _ in 0..f as usize{let p=self.boards[c.side].iter().position(|id|id==&x);self.death(&Context{pos:p,..c.clone()},&x)?;}}}}},
 "dragonCombatBuff"=>{for x in self.boards[c.side].clone(){if tribe(self.m(&x),"龙")?{self.gain(c,Some(id),&x,2.*f+mc(&m,"dragonBuff"),2.*f+mc(&m,"dragonBuff"))?;}}},
 "undeadPlague"=>self.scale(c.side,"undead",2.*f,0.)?,
 "goldenNeighbors"=>{let n=f*(1.+self.boards[c.side].iter().filter(|x|truth(&self.m(x)["golden"])).count() as f64);let mut a=a.clone();a["target"]=json!("adjacent");for x in self.targets(c,id,&a)?{self.gain(c,Some(id),&x,n,0.)?;}},
 "satelliteGrowing"=>{if let Some(t)=&c.event{let n=(2.+mc(&m,"satelliteSize"))*f;self.gain(c,Some(id),t,n,n)?;self.mm(t)["magneticCount"]=json!(num(&self.m(t)["magneticCount"])+1.);}bump(self.mm(id),"satelliteSize",1.);},
 "preview"=>self.preview(c,id,a)?,"timewarp"=>self.timewarp(c,id,a)?,
 "gold"|"goldNext"|"goldCap"|"freeRefresh"|"discountSpell"|"fodder"|"armor"|"generate"|"randomSpell"|"draw"|"drawType"|"drawId"|"discoverMinion"|"discoverSpell"|"bounty"|"chromadrake"|"lastSpell"|"goldenFour"|"craft"|"craftScale"|"lockbox"|"morgltonParent"=>{let context=crate::recruit_effects::Context{depth:c.depth,target:c.target.clone(),event_minion:c.event.clone(),amount:c.amount,..Default::default()};self.recruit(c.side,|r|{r.state["__detached"].as_array_mut().unwrap().push(m.clone());r.effect(&context,&m,a)})?;},
 "spell"=>{for _ in 0..n as usize{let card=self.make(&format!("s14_{}",str_field(a,"id")?),false)?;if a["event"]=="combat"{self.cast(c,card)?;}else{self.recruit(c.side,|r|r.put_hand(card,true))?;}}},
 "castTavern"=>{for _ in 0..n as usize{let card=self.make(&format!("s14_{}",str_field(a,"id")?),false)?;self.cast(c,card)?;}},
 "adjacentSpell"|"rightSpell"=>{let mut a2=a.clone();a2["target"]=json!("adjacent");let targets=if op=="rightSpell"{self.boards[c.side].iter().position(|x|x==id).and_then(|i|self.boards[c.side].get(i+1).cloned()).into_iter().collect()}else{self.targets(c,id,&a2)?};for x in targets{for _ in 0..f as usize{let card=self.make(&format!("s14_{}",str_field(a,"id")?),false)?;self.cast(&Context{target:Some(x.clone()),..c.clone()},card)?;}}},
 _=>return Err(format!("RUST_COMBAT_EFFECT_INCOMPLETE: {op} on {}",m["id"]))
 }Ok(())}
 pub fn cast(&mut self,c:&Context,card:Value)->Result<()>{let id=uid(&card);self.cards.insert(id.clone(),card);self.run(c,&id,"cast")}
}
