use crate::recruit::Recruit;
use crate::recruit_effects::{Context, keyword};
use crate::{Result, abilities, arr, catalog, def, has, num, powers, primitives, stats, str_field, tribe, truth};
use serde_json::{Value,json};
impl Recruit {
    pub fn refill(&mut self, keep:bool, keep_selected:bool, refreshed:bool)->Result<()> {
        let ctx=Context::default();
        let seer=refreshed && self.item("BG32_MagicItem_366")>0 && self.bump(&format!("seerRefresh:{}",self.state["turn"]),1.)<=2.*self.item("BG32_MagicItem_366") as f64;
        let tier=num(&self.state["tier"]);let high=self.item("BG30_MagicItem_998")>0;
        let allowed=|d:&Value| (if seer {num(&d["tier"])==6.}else{num(&d["tier"])<=tier}) && (!high || num(&d["tier"])>2.);
        if !keep {let frozen=if keep_selected {arr(&self.state["season"]["frozenMinions"]).to_vec()}else{vec![]};let mut kept=vec![];
            for mut m in arr(&self.state["shop"]).to_vec(){if frozen.contains(&m["uid"]){kept.push(m)}else{self.release(&mut m)?;}}
            self.state["shop"]=json!(kept);self.state["season"]["spellShop"]=json!([]);
        }
        self.state["season"]["frozenMinions"]=json!([]);
        if refreshed && self.count("warbandRefresh")!=0. {self.state["season"]["counters"]["warbandRefresh"]=json!(0);for m in arr(&self.state["board"]).to_vec().into_iter().take(7){let mut c=self.make(str_field(&m,"id")?,truth(&m["golden"]),false)?;c=self.apply_shop(c)?;self.state["shop"].as_array_mut().unwrap().push(c);}}
        let size=((if self.item("BG30_MagicItem_841")>0 {6.} else {num(&catalog().data["shopSize"][tier as usize])-if powers::has(&self.state,"sindragosa"){1.}else{0.}})+self.count("prizeExtraShop")).min(7.) as usize;
        while arr(&self.state["shop"]).len()<size {let Some(mut c)=self.draw(allowed)? else{break};c=self.apply_shop(c)?;if self.count("prizeExtraShop")!=0. && arr(&self.state["shop"]).len() as f64>=size as f64-self.count("prizeExtraShop"){stats::add(&mut c,2.,2.);}self.state["shop"].as_array_mut().unwrap().push(c);}
        if arr(&self.state["season"]["spellShop"]).is_empty() {if let Some(c)=self.draw_spell(allowed)?{self.state["season"]["spellShop"]=json!([c]);}}
        if num(&self.state["season"]["fodder"])>0. {self.state["season"]["fodder"]=json!(num(&self.state["season"]["fodder"])-1.);let ds=arr(&self.state["board"]).iter().filter(|m|tribe(m,"恶魔").unwrap_or(false)).cloned().collect::<Vec<_>>();let i=self.index(ds.len());if i<ds.len(){let m=&ds[i];let n=2.+4.*self.item("BG35_MagicItem_151") as f64+15.*self.item("BG35_MagicItem_151t") as f64;self.gain(str_field(m,"uid")?,n,n,None,0)?;self.log(format!("{}吞食恶魔饲料，获得+2/+2。",str_field(def(str_field(m,"id")?)?,"name")?));}}
        let i=self.index(arr(&self.state["shop"]).len());if i<arr(&self.state["shop"]).len(){let d=self.state["season"]["buffs"]["refresh"].clone();stats::add(&mut self.state["shop"][i],num(&d["attack"]),num(&d["health"]));}
        if refreshed {self.state["upgrade"]=json!((num(&self.state["upgrade"])-self.item("BG36_MagicItem_300") as f64).max(0.));self.trinket_event(&ctx,"refresh",None)?;for uid in self.board_ids(){self.run_event(&ctx,&uid,"refresh")?;}}
        let barrage=num(&self.state["season"]["buffs"]["gemBarrage"]["attack"]);if barrage!=0. {for m in arr(&self.state["shop"]).to_vec(){let source=self.make("s14_BG20_GEM",false,false)?;self.effect(&Context{target:Some(str_field(&m,"uid")?.into()),..ctx.clone()},&source,&json!({"event":"cast","op":"gem","target":"selected","amount":barrage}))?;}}
        if powers::has(&self.state,"varden") {let highest=arr(&self.state["shop"]).iter().enumerate().max_by(|(ai,a),(bi,b)|num(&def(a["id"].as_str().unwrap()).unwrap()["tier"]).total_cmp(&num(&def(b["id"].as_str().unwrap()).unwrap()["tier"])).then(bi.cmp(ai))).map(|(_,m)|m.clone());if let Some(mut c)=highest && arr(&self.state["shop"]).len()<7 {let original=c["uid"].clone();c["uid"]=self.make(str_field(&c,"id")?,false,false)?["uid"].clone();c["copies"]=json!({});self.state["season"]["frozenMinions"]=json!([original,c["uid"]]);self.state["shop"].as_array_mut().unwrap().push(c);}}
        if powers::has(&self.state,"enhance"){for _ in 0..2{let i=self.index(arr(&self.state["shop"]).len());if i<arr(&self.state["shop"]).len(){let k=["嘲讽","圣盾","风怒","复生"][self.index(4)];keyword(&mut self.state["shop"][i],k);}}}
        if powers::has(&self.state,"ysera") && arr(&self.state["shop"]).len()<7 {if let Some(mut c)=self.draw(|d|num(&d["tier"])<=tier&&(arr(&d["races"]).contains(&json!("龙"))||d["tribe"]=="全部"))?{c=self.apply_shop(c)?;self.state["shop"].as_array_mut().unwrap().push(c);}}
        Ok(())
    }
    pub fn notify_summon(&mut self,ctx:&Context,uid:&str)->Result<()> {let m=self.owned(uid)?;let next=Context{event_minion:Some(uid.into()),..ctx.clone()};for id in self.board_ids(){self.run_event(&next,&id,"summonAny")?;}self.trinket_event(&next,"summon",None)?;if m["id"]=="s14_BG_TTN_401"{self.bump("automatonSummons",1.);self.mbump(uid,"automatonSelf",1.)?;self.sync_all()?;}for id in self.board_ids(){if id!=uid {if tribe(&m,"野兽")?{self.run_event(&next,&id,"summonBeast")?;}if tribe(&m,"机械")?{self.run_event(&next,&id,"summonMech")?;}}}Ok(())}
    pub fn summon(&mut self,ctx:&Context,m:Value)->Result<()> {if arr(&self.state["board"]).len()>=7{return Ok(())}let uid=str_field(&m,"uid")?.to_owned();let pos=ctx.summon_cursor.as_ref().map(|c|c.get()).unwrap_or(ctx.source_pos).min(arr(&self.state["board"]).len());self.state["board"].as_array_mut().unwrap().insert(pos,m);if let Some(c)=&ctx.summon_cursor{c.set(pos+1);}self.notify_summon(ctx,&uid)}
    pub fn death(&mut self,ctx:&Context,uid:&str)->Result<()> {let m=self.owned(uid)?;let mut repeats=1;let mut titus=0;for x in arr(&self.state["board"]){if has(x,"repeatAllTriggers")?{repeats=repeats.max(if truth(&x["golden"]){3}else{2});}if num(&x["health"])>0.&&has(x,"titus")?{titus+=if truth(&x["golden"]){2}else{1};}}
        for _ in 0..repeats+titus {self.run_event(ctx,uid,"death")?;self.gift_event(ctx,uid,"death")?;if abilities(&m)?.iter().any(|a|a["event"]=="death"){self.bump("deathrattles",1.);self.sync_all()?;for id in self.board_ids(){self.run_event(&Context{event_minion:Some(uid.into()),..ctx.clone()},&id,"deathTriggered")?;}}}Ok(())}
    pub fn destroy_recruit(&mut self,ctx:&Context,uid:&str)->Result<bool>{let Some(pos)=arr(&self.state["board"]).iter().position(|m|m["uid"]==uid)else{return Ok(false)};let m=self.detach(uid)?;let next=Context{source_pos:pos,summon_cursor:Some(std::rc::Rc::new(std::cell::Cell::new(pos))),..ctx.clone()};self.death(&next,uid)?;self.trinket_event(&Context{event_minion:Some(uid.into()),..ctx.clone()},"destroy",None)?;
        if m["id"]=="s14_BG34_690"{for _ in 0..self.item("BG36_MagicItem_204"){let c=self.make(str_field(&m,"id")?,false,false)?;self.trinket_card(c)?;}}
        if arr(&m["keywords"]).contains(&json!("复生"))&&arr(&self.state["board"]).len()<7{let c=self.make(str_field(&m,"id")?,truth(&m["golden"]),false)?;let mut c=stats::global(&self.state,c)?;c["health"]=json!(1);c["keywords"].as_array_mut().unwrap().retain(|k|k!="复生");let revived=str_field(&c,"uid")?.to_owned();self.summon(&next,c)?;for id in self.board_ids(){self.run_event(&Context{event_minion:Some(revived.clone()),..ctx.clone()},&id,"reborn")?;}}
        let mut released=self.owned(uid)?;self.release(&mut released)?;*self.owned_mut(uid)?=released;Ok(true)}
    pub fn linked_cards(&mut self,ctx:&Context,spells:bool,aberrations:bool)->Result<()> {let tier=num(&self.state["tier"]);let mut cards=vec![];for _ in 0..2{let m=if spells{self.draw_spell(|_|true)?}else{self.draw(|d|num(&d["tier"])<=tier&&(!aberrations||arr(&d["races"]).contains(&json!("畸变怪"))||d["tribe"]=="全部"))?};if let Some(m)=m{cards.push(m);}}let group=cards.first().map(|m|m["uid"].clone());for mut m in cards{m["discardGroup"]=group.clone().unwrap();self.give(ctx,m)?;}Ok(())}
    pub fn magnetize(&mut self,ctx:&Context,host:&str,attachment:Value)->Result<()> {let aid=self.remember_card(attachment)?;self.run_event(ctx,&aid,"volumizer")?;let attachment=self.owned(&aid)?;let factor=num(&self.owned(host)?["counters"]["magneticArmed"]);let factor=if factor!=0.{factor}else{1.};self.mbump(host,"magneticArmed",-num(&self.owned(host)?["counters"]["magneticArmed"]))?;
        let mut targets=vec![(host.to_owned(),factor,true)];for m in arr(&self.state["board"]){if m["uid"]!=host&&has(m,"repeatMagnetize")?{targets.push((str_field(m,"uid")?.into(),factor*if truth(&m["golden"]){2.}else{1.},false));}}
        for (uid,repeats,pool) in targets{self.gain(&uid,num(&attachment["attack"])*repeats,num(&attachment["health"])*repeats,Some(&attachment),ctx.depth)?;let target=self.owned_mut(&uid)?;target["magneticCount"]=json!(num(&target["magneticCount"])+repeats);for k in arr(&attachment["keywords"]){keyword(target,k.as_str().unwrap());}if !target["extraAbilities"].is_array(){target["extraAbilities"]=json!([]);}for _ in 0..repeats as usize{for a in abilities(&attachment)?{target["extraAbilities"].as_array_mut().unwrap().push(primitives::copy_ability(&attachment,&a)?);}}if pool{for (id,n) in attachment["copies"].as_object().unwrap(){target["copies"][id]=json!(num(&target["copies"][id])+num(n));}}}Ok(())}
}
