use crate::recruit::Recruit;
use crate::recruit_effects::Context;
use crate::{Result,abilities,arr,catalog,def,has,num,powers,str_field,tribe,truth,trinkets};
use serde_json::{Value,json};
use tavern_combat_prototype::Random;
impl Recruit {
 pub fn create(request:&Value)->Result<Self>{
  let data=&catalog().data;let hero_id=request["hero"].as_str().unwrap_or("s14_lich");let id=arr(&data["heroPool"]).iter().find(|id|id.as_str()==Some(hero_id)).unwrap_or(&data["heroPool"][0]);let hero=arr(&data["heroes"]).iter().find(|h|h["id"]==*id).ok_or("Unknown active hero")?;
  let shared=request.get("options").filter(|s|s["tribes"].is_array());let mut ctx=Self{state:json!({}),rng:Random::new(request["seed"].as_u64().ok_or("Seed must be uint32")? as u32),serial:request["uidCounter"].as_u64().unwrap_or(0),logs:request["recordLogs"].as_bool().unwrap_or(true)};
  let mut types=if let Some(s)=shared {arr(&s["tribes"]).to_vec()}else{let mut types=arr(&data["tribes"]).iter().filter(|t|*t!="畸变怪").cloned().collect::<Vec<_>>();ctx.shuffle(&mut types);types.truncate(4);types.insert(0,json!("畸变怪"));types};let required=&data["heroTribes"][id.as_str().unwrap()];if shared.is_none()&&!required.is_null()&&!types.contains(required){types[1]=required.clone();}
  let paradoxes=arr(&data["minionPool"]).iter().filter(|id|{let source=def(id.as_str().unwrap()).unwrap()["sourceId"].as_str().unwrap_or("");source.starts_with("BG36_360t")&&!(types.contains(&json!("亡灵"))&&source=="BG36_360t4")}).cloned().collect::<Vec<_>>();let paradox=if let Some(pool)=shared.and_then(|s|s.get("pool")){paradoxes.iter().find(|id|pool.get(id.as_str().unwrap()).is_some()).cloned()}else{paradoxes.get(ctx.index(paradoxes.len())).cloned()};
  let mut initial=serde_json::Map::new();for id in arr(&data["minionPool"]){let d=def(id.as_str().unwrap())?;let available=arr(&d["races"]).is_empty()||d["tribe"]=="全部"||arr(&d["races"]).iter().any(|t|types.contains(t));if available&&(!d["sourceId"].as_str().unwrap_or("").starts_with("BG36_360t")||Some(id)==paradox.as_ref()){initial.insert(id.as_str().unwrap().into(),data["poolCopies"][num(&d["tier"]) as usize].clone());}}
  let mut opponent_ids=arr(&data[if shared.is_some(){"heroPool"}else{"aiHeroPool"}]).iter().filter(|v|*v!=id).cloned().collect::<Vec<_>>();ctx.shuffle(&mut opponent_ids);let opponents=opponent_ids.iter().take(7).map(|id|{let h=arr(&data["heroes"]).iter().find(|h|h["id"]==*id).unwrap();json!({"name":h["name"],"hero":id,"health":h["health"],"armor":num(&h["armor"]),"tier":1,"board":[]})}).collect::<Vec<_>>();let deity=if let Some(d)=shared.and_then(|s|s.get("deity")).filter(|d|truth(d)){d.clone()}else{json!(if arr(&data["rules"]["deityRestrictedHeroes"]).contains(id)||ctx.index(2)==0{"BGFYM_000"}else{"BGFYM_011"})};
  ctx.state=json!({"version":1,"hero":id,"turn":1,"gold":3,"tier":1,"upgrade":if id=="s14_millhouse"{6}else{5},"health":hero["health"],"frozen":false,"powerUsed":false,"shop":[],"hand":[],"board":[],"pool":shared.and_then(|s|s.get("pool")).cloned().unwrap_or(json!(initial)),"opponents":opponents,"nextOpponent":0,"logs":[format!("第{}赛季 · {}练习场。每局随机开放5个随从类型。",data["seasonMeta"]["season"],data["patch"].as_str().unwrap())],"battles":[],"discovery":[],"rewards":[],"pogo":0,"triples":0,"purchases":0,"refreshes":0,"phase":"recruit","battle":null,"__detached":[],"season":{"patch":data["patch"],"deity":{"id":deity,"attack":1,"health":1,"golden":false},"armor":num(&hero["armor"]),"tribes":types,"spellShop":[],"initialPool":initial,"freeRefresh":0,"nozdormuRefreshTurn":0,"nextGold":0,"maxGold":10,"giftsUsed":0,"giftUsedTurn":0,"discoveryKind":"","pendingDiscoveries":[],"trinkets":[],"trinketOffers":[],"trinketDone":[],"buffs":{},"fodder":0,"spellDiscount":0,"healthRefreshes":0,"healthRefreshUses":{},"playedTurn":0,"goldenPlayed":0,"spellsCast":0,"battlecries":0,"deaths":0,"trinketBuys":0,"heroPowerUses":0,"heroPowerUsesTurn":0,"elementalsPlayed":0}});
  ctx.refill(false,false,false)?;if powers::has(&ctx.state,"afk"){ctx.state["gold"]=json!(0);}for (power,card) in [("curator","s14_TB_BaconShop_HP_033t"),("nzoth","s14_TB_BaconShop_HP_105t")]{if powers::has(&ctx.state,power){let m=ctx.make(card,false,false)?;ctx.state["board"].as_array_mut().unwrap().push(m);}}
  ctx.hero_start(&Context::default())?;if id=="s14_finley"{ctx.offer_powers("finley",&[])?;}if id=="s14_nguyen"{ctx.state["season"]["powerCycle"]=json!(true);ctx.offer_powers("nguyen",&[])?;}Ok(ctx)
 }
 pub fn end_effects(&mut self)->Result<()>{let ctx=Context::default();let mut repeats=1;for m in arr(&self.state["board"]){if has(m,"drakkari")?{repeats=repeats.max(if truth(&m["golden"]){3}else{2});}}repeats+=self.item("BG32_MagicItem_367");for _ in 0..repeats{self.hero_end(&ctx)?;self.trinket_event(&ctx,"end",None)?;for uid in self.board_ids(){self.run_event(&ctx,&uid,"end")?;self.gift_event(&ctx,&uid,"end")?;}
  for id in arr(&self.state["season"]["trinkets"]).to_vec(){let id=id.as_str().unwrap();if ["BG36_MagicItem_302","BG36_MagicItem_302t"].contains(&id){let g=num(&self.state["season"]["goldenPlayed"]);for m in self.state["board"].as_array_mut().unwrap(){crate::stats::add(m,if id.ends_with("302t"){4.+g}else{1.+g},if id.ends_with("302t"){2.+g}else{1.+g});}}
  if ["BG36_MagicItem_810","BG36_MagicItem_810t"].contains(&id){let mut m=self.make("s14_BG31_171t",false,false)?;let n=if id.ends_with("810t"){12.}else{4.}+self.count(&format!("trinketSpells:{}",self.state["turn"]));m["attack"]=json!(n);m["health"]=json!(n);self.trinket_card(m)?;}}
  for _ in 0..self.item("BG36_MagicItem_212"){let cards=arr(&self.state["board"]).iter().filter(|m|abilities(m).unwrap().iter().any(|a|a["event"]=="death")).take(2).cloned().collect::<Vec<_>>();for m in cards{self.death(&ctx,str_field(&m,"uid")?)?;}}
  for _ in 0..self.item("BG36_MagicItem_214"){for uid in self.board_ids(){self.run_event(&ctx,&uid,"rally")?;}}
  for _ in 0..self.item("BG36_MagicItem_812"){let m=arr(&self.state["board"]).iter().find(|m|tribe(m,"机械").unwrap_or(false)).cloned();if let Some(m)=m{let spell=self.make("s14_BG36_624",false,false)?;self.cast_spell(&Context{target:Some(str_field(&m,"uid")?.into()),..ctx.clone()},&spell)?;}}
  if let Some(id)=self.state["season"]["lastSpell"].as_str().map(str::to_owned){for _ in 0..3*self.item("BG36_MagicItem_372"){let card=self.make(&id,false,false)?;self.trinket_card(card)?;}}}
  for _ in 0..self.count(&format!("unlimitedCoins:{}",self.state["turn"])) as usize{let card=self.make("s14_BGS_Treasures_014",false,false)?;self.put_hand(card,true)?;}let mut kept=vec![];for mut m in arr(&self.state["hand"]).to_vec(){if truth(&m["expires"]){self.release(&mut m)?;}else{kept.push(m);}}self.state["hand"]=json!(kept);if let Some(pending)=self.state["season"]["pendingTrinketCards"].as_array_mut(){pending.retain(|m|!truth(&m["expires"]));}self.flush()?;Ok(())
 }
 pub fn offer_trinkets(&mut self,school:&str)->Result<()>{let output=trinkets::offer(self.state.clone(),school,self.rng.state)?;self.state=output["state"].clone();self.rng.state=output["rng"].as_u64().unwrap() as u32;self.rng.draws+=output["draws"].as_u64().unwrap() as u32;Ok(())}
 pub fn start_effects(&mut self)->Result<()>{let ctx=Context::default();for chest in arr(&self.state["hand"]).to_vec(){if chest["id"]=="s14_BG36_520t"&&truth(&chest["lockedUntil"])&&num(&chest["lockedUntil"])<=num(&self.state["turn"]){self.detach(str_field(&chest,"uid")?)?;let tier=num(&self.state["tier"]);let cards=self.pool_cards()?.into_iter().filter(|d|num(&d["tier"])<=tier&&!arr(&d["races"]).is_empty()).collect::<Vec<_>>();if let Some(d)=cards.get(self.index(cards.len())){let card=self.make(str_field(d,"id")?,true,false)?;self.put_hand(card,true)?;}self.log("上锁宝箱已打开，获得金色随从。".into());}}
 self.state["season"]["freeRefresh"]=json!(num(&self.state["season"]["freeRefresh"])+self.count("prizeRefresh"));for key in ["playedTurn","trinketBuys","healthRefreshes","goldSpentTurn"]{self.state["season"][key]=json!(0);}self.state["season"]["healthRefreshUses"]=json!({});let turn=num(&self.state["turn"]);let tier=num(&self.state["tier"]);
 for zone in ["board","hand","shop"]{for m in self.state[zone].as_array_mut().unwrap(){m["activated"]=json!(false);if m["counters"].is_object(){m["counters"]["magneticArmed"]=json!(0);m["counters"]["purchaseArmed"]=json!(0);}if truth(&m["lockedUntil"])&&num(&m["lockedUntil"])<=turn{m.as_object_mut().unwrap().remove("lockedUntil");}if truth(&m["lockedTier"])&&num(&m["lockedTier"])<=tier{m.as_object_mut().unwrap().remove("lockedTier");}m["rebornNext"]=json!(false);if m["temporary"].is_object(){m["attack"]=json!((num(&m["attack"])-num(&m["temporary"]["attack"])).max(0.));m["health"]=json!((num(&m["health"])-num(&m["temporary"]["health"])).max(1.));let ks=arr(&m["temporary"]["keywords"]).to_vec();m["keywords"].as_array_mut().unwrap().retain(|k|!ks.contains(k));m.as_object_mut().unwrap().remove("temporary");}}}
 for delayed in arr(&self.state["season"]["delayed"]).to_vec(){if num(&delayed["turn"])==turn&&(!truth(&delayed["win"])||self.state["battles"][0]["result"]=="win"){for uid in self.board_ids(){if !truth(&delayed["uid"])||delayed["uid"]==uid{for _ in 0..num(&delayed["amount"]) as usize{self.gain(&uid,num(&delayed["attack"]),num(&delayed["health"]),None,0)?;}}}}}if let Some(ds)=self.state["season"]["delayed"].as_array_mut(){ds.retain(|d|num(&d["turn"])>turn);}
 for uid in self.board_ids(){self.run_event(&ctx,&uid,"start")?;self.run_event(&ctx,&uid,"spellcraft")?;}if !truth(&self.state["season"]["powerChoice"]){self.start_power_effects()?;}if self.state["season"]["powerChoice"]["mode"]!="nguyen"{self.hero_start(&ctx)?;}
 for slot in arr(&self.state["season"]["mysteryCubeSlots"]).to_vec(){if self.state["season"]["trinkets"][num(&slot) as usize]!="BG30_MagicItem_703"{if !self.state["season"]["pendingTrinketChoices"].is_array(){self.state["season"]["pendingTrinketChoices"]=json!([]);}self.state["season"]["pendingTrinketChoices"].as_array_mut().unwrap().push(json!({"slot":slot,"school":"LESSER_TRINKET","free":true}));}}
 self.trinket_event(&ctx,"start",None)?;for id in arr(&self.state["season"]["trinkets"]).to_vec(){self.trinket_start(&ctx,id.as_str().unwrap(),false,arr(&self.state["season"]["trinkets"]).iter().rposition(|x|x==&id).unwrap())?;}
 let early=self.count("earlyGreater");let greater=if early!=0.{early}else if powers::has(&self.state,"buttons"){8.}else{9.};if (turn==6.||turn==greater||powers::has(&self.state,"marin")&&turn==5.)&&!arr(&self.state["season"]["trinketDone"]).contains(&self.state["turn"]){let school=if turn<=6.||self.item("BG35_MagicItem_818")>0&&self.count("orbNextDone")==0.{"LESSER_TRINKET"}else{"GREATER_TRINKET"};if turn==greater{self.bump("orbNextDone",1.);}self.offer_trinkets(school)?;let turn=self.state["turn"].clone();self.state["season"]["trinketDone"].as_array_mut().unwrap().push(turn);}Ok(())
 }
 pub fn advance_recruit(&mut self)->Result<()>{if self.state["season"].get("nozdormuRefreshTurn").is_none(){if powers::has(&self.state,"nozdormu")&&num(&self.state["season"]["freeRefresh"])>0.{self.state["season"]["freeRefresh"]=json!(num(&self.state["season"]["freeRefresh"])-1.);}self.state["season"]["nozdormuRefreshTurn"]=self.state["turn"].clone();}
 self.state["turn"]=json!(num(&self.state["turn"])+1.);let max=num(&self.state["season"]["maxGold"]);self.state["gold"]=json!((10f64.min(num(&self.state["turn"])+2.)+max-10.+num(&self.state["season"]["nextGold"])).min(max));self.state["season"]["nextGold"]=json!(0);self.state["season"].as_object_mut().unwrap().remove("temporaryGoldCap");self.state["upgrade"]=json!((num(&self.state["upgrade"])-1.).max(0.));self.state["powerUsed"]=json!(false);self.state["season"]["heroPowerUsesTurn"]=json!(0);if let Some(ps)=self.state["season"]["powerProgress"].as_object_mut(){for p in ps.values_mut(){p["turnUses"]=json!(0);}}self.state["powerUsed"]=powers::state(&self.state,self.state["hero"].as_str().unwrap())?["used"].clone();self.state["phase"]=json!("recruit");self.state["battle"]=Value::Null;if truth(&self.state["season"]["powerCycle"]){self.offer_powers("nguyen",&[])?;}else if powers::has(&self.state,"genn")&&num(&self.state["turn"])>=4.{self.offer_powers("genn",&[])?;}self.start_effects()?;self.refill(truth(&self.state["frozen"]),true,false)?;self.state["frozen"]=json!(false);self.settle_trinkets()?;Ok(())}
}
