import type { Ability } from "../data";
const a = (event: string, op: string, rest: Partial<Ability> = {}): Ability => ({ event, op, ...rest });
const b = (event: string, attack: number, health: number, target = "self", tribe?: string) => a(event, "buff", { attack, health, target, tribe });
const choice = (id: string, target?: string, tribe?: string) => [a("choice", "choose", { id, target, tribe })];
// Each entry is backed by an explicit engine operation; missing entries stay out of the shop.
export const expandedMinions: Record<string, Ability[]> = {
  BG28_583: [a("gemPlayed", "roogug")],
  BG36_372: [a("aura", "lowHeroHealth", { amount: 15, attack: 15, health: 15 })],
  BG25_034: [a("battlecry", "golden", { target: "selected", tier: 6 })],
  BG26_149: [a("aura", "repeatMagnetize")],
  BG27_016: [a("battlecry", "scale", { key: "shop", attack: 8, health: 8 }), a("death", "scale", { key: "shop", attack: 8, health: 8 })],
  BG27_017: [a("rally", "ravager")],
  BG27_514: [a("spellcraft", "zarjiraCraft")],
  BG31_999: [a("combat", "salvage"), a("death", "salvageSummon")],
  BG34_145: [a("end", "ownStatsHand")],
  BG34_319: [a("battlecry", "draw", { tier: 6 }), a("death", "draw", { tier: 6 }), a("rally", "draw", { tier: 6 })],
  BG34_320: [a("rally", "buff", { target: "menagerie", attack: 15, health: 15, permanent: true })],
  BG34_322: [a("summonCombat", "kodoStats")],
  BG34_950: [a("buyMinion", "stoneSlab")],
  BG36_333: [a("rally", "jailbird")],
  BG25_806: [a("death", "randomBeastSix")],
  BG26_175: [a("aura", "elementalWildcard")],
  BG27_556: [a("combat", "pendingHandMurloc")],
  BG28_303: [a("battlecry", "destroyUndead", { target: "selected", tribe: "亡灵", key: "copy" })],
  BG32_340: [a("battlecry", "destroyUndead", { target: "selected", tribe: "亡灵", key: "discover" })],
  BG29_503: [a("battlecry", "discoverMagnetize", { target: "selected", tribe: "机械" })],
  BG29_813: [a("aura", "keepAdjacentDragons")],
  BG31_835: [a("friendlyDeath", "periodic", { amount: 4, key: "undeadHand" }), a("death", "summonRemembered")],
  BG32_822: [a("combat", "dragonCombatBuff"), a("tavernSpell", "growDragonBuff")],
  BG33_155: [a("demonDamage", "buff", { attack: 2, health: 2, permanent: true })],
  BG33_821: [a("battlecry", "bounty"), a("death", "bounty")],
  BG33_822: [a("rally", "bounty")],
  BG33_823: [a("spentGold", "periodic", { amount: 9, key: "bounty" })],
  BG33_825: [a("aura", "repeatBounty")],
  BG33_891: [a("buySpell", "learnSpell")],
  BG34_633: [a("battlecry", "chromadrake"), a("death", "chromadrake")],
  BG36_240: [a("activate", "chromadrake")], BG36_242: [a("rally", "chromadrake")],
  BG35_602: [a("summonBeast", "growingBeast")],
  BG35_604: [a("death", "summon", { id: "BG19_010", amount: 2 })],
  BG19_010: [a("death", "summon", { id: "BG19_010t" })],
  BG36_201: [a("activate", "fishbait", { target: "selectedShop" })],
  BG36_206: [a("sell", "fishbaitRefresh")],
  BG36_520: [a("battlecry", "lockbox")], BG36_521: [a("death", "lockbox")],
  BG36_523: [a("spentGold", "periodic", { amount: 5, key: "lockbox" })],
  BGS_012: [a("death", "kangor")],
  BG34_634t: [a("battlecry", "randomSpell", { cost: 2 })],
  BG34_635t: [a("battlecry", "scale", { key: "spell", health: 1 })],
  BG34_636t: [b("battlecry", 1, 3, "others", "龙")],
  BG34_637t: [b("battlecry", 3, 1, "others", "龙")],
  BG34_638t: [a("battlecry", "scale", { key: "spell", attack: 1 })],
  BG35_883: [a("aura", "repeatFriendlySpell")],
  BG23_009: [a("aura", "permanentSpellcraft")],
  BG26_505: [a("aura", "copySpellcraft")],
  BG23_007: [a("spellcraft", "craft", { attack: 2, health: 2, key: "nagaWindfury" })],
  BG31_924: [a("spellcraft", "craftProgress", { attack: 1, health: 1 })],
  BG31_920: [a("spellcraft", "craftNaga")],
  BG33_319: [a("spellcraft", "craftStatsSpell")],
  BG27_084: choice("BG27_084", "selected", "野兽"),
  BG30_123: choice("BG30_123"), BG31_320: choice("BG31_320"),
  BG32_237: choice("BG32_237"), BG36_330: choice("BG36_330"),
  BG36_332: choice("BG36_332"), BG36_341: choice("BG36_341"),
  BG31_327: [a("aura", "bothChoices")],
  BG31_323: [a("choosePlayed", "gem", { target: "others", tribe: "野猪人" })],
  BG36_331: [a("rally", "randomChoice")],
  BG24_018: [a("sell", "lossGold", { amount: 4 })],
  BG24_715: [a("sell", "scoutDiscover")],
  BG25_013: [b("friendlyDeath", 1, 0)],
  BG25_016: [a("rally", "stripDefenses")],
  BG23_318: [a("death", "killKiller")],
  BG26_137: [b("handPlayMurloc", 6, 6)],
  BG26_525: [a("battlecry", "discoverDemonDamage")],
  BG26_810: [a("spentGold", "periodic", { amount: 5, key: "pirateAttack" })],
  BG26_814: [a("battlecry", "goldHealth", { target: "others", tribe: "海盗" })],
  BG31_824: [a("spentGold", "periodic", { amount: 5, key: "piratePair" })],
  BG28_633: [a("anySpell", "periodic", { amount: 3, key: "consume" })],
  BG29_300: [b("damaged", 2, 1, "randomHand")],
  BG31_035: [a("playNaga", "spellProgressBuff", { attack: 1, health: 1 })],
  BG31_925: [a("death", "spellProgressBuff", { attack: 2, health: 1, target: "all", tribe: "纳迦" })],
  BG32_235: [a("end", "goldenNeighbors")],
  BG32_236: [a("aura", "alwaysGolden")],
  BG32_324: [a("friendlyDeath", "periodic", { amount: 3, key: "butchering" })],
  BG32_330: [a("handCombat", "summonSelfCopy")],
  BG32_837: [a("end", "adjacentSpell", { id: "BG28_845" })],
  BG32_841: [a("battlecry", "scale", { key: "elementalGrant", attack: 2 })],
  BG32_842: [a("death", "scale", { key: "elementalGrant", health: 2 })],
  BG33_430: [a("otherAttack", "gem", { target: "event" })],
  BG33_893: [a("cardPlayed", "lowTierMurlocs")],
  BG34_140: [a("rally", "summonHand", { key: "attack" })],
  BG34_142: [a("combat", "handAttack")],
  BG34_604: [a("rally", "targetAttack")],
  BG34_682: [a("death", "generate", { id: "BG34_689" })],
  BG34_683: [a("battlecry", "generate", { id: "BG34_689" })],
  BG34_684: [a("end", "generate", { id: "BG28_698" })],
  BG34_690: [a("death", "undeadPlague")],
  BG34_858: [a("spentGold", "periodic", { amount: 7, key: "rideWinds" })],
  BG34_925: [a("rally", "rightSpell", { id: "BG28_518" })],
  BG35_123: [a("end", "lastSpell")],
  BG35_140: [a("battlecry", "morglton", { attack: 3, target: "others", tribe: "鱼人" })],
  BG35_141: [a("battlecry", "morglton", { health: 3, target: "others", tribe: "鱼人" })],
  BG35_142: [a("end", "morgltonParent")],
  BG35_143: [a("battlecry", "generate", { id: "BG35_149" }), a("death", "generate", { id: "BG35_149" })],
  BG35_341: [a("aura", "spellAura", { attack: 1, health: 1 })],
  BG35_814: [a("aura", "shieldAtSix")],
  BG35_921: [a("aura", "globalStats", { key: "tavernSpells", attack: 2, health: 1 })],
  BG36_180: [a("activate", "armPurchase")],
  BG36_208: [a("afterAttack", "rallyDeathrattle")],
  BG36_209: [a("afterAttack", "scale", { key: "beetle", attack: 5, health: 5 }), a("death", "summon", { id: "BG28_603t", goldenAmount: 2, summonGolden: false })],
  BG36_343: [a("battlecry", "goldenFour")],
  BG36_344: [a("discovered", "pirateDiscover")],
  BG36_351: [a("rally", "scale", { key: "elementalGrant", attack: 2, health: 2 })],
  BG36_352: [a("playElemental", "periodic", { amount: 3, key: "consumeHighest" })],
  BG36_506: [a("activate", "armMagnetic")],
  BG36_508: [a("activate", "castRandom", { amount: 2 })],
  BG36_510: [a("targetSpell", "gem", { target: "adjacent" })],
  BG36_511: [a("activate", "rebornDestroy", { target: "selected", tribe: "亡灵" })],
  BG36_514: [a("reborn", "shieldReborn")],
  BG36_515: [a("reborn", "inheritReborn")],
  BG36_524: [a("aura", "globalStats", { key: "goldenPlayed", attack: 7, health: 7 })],
  BG36_621: [a("activate", "randomShopUpgrade")],
  BG36_733: [a("heroDamage", "periodic", { amount: 4, key: "pastry" })],
  BG36_763: [a("dealtDamage", "parrotGold")],
  BG36_851: [a("playMech", "satelliteGrowing")],
  BG36_853: [a("spellMech", "satellite", { attack: 4, health: 4, target: "event" })],
  BG26_152: [a("end", "magneticGrowth", { attack: 4, health: 5 })],
  BG25_008: [a("aura", "globalStats", { key: "knightDeaths", attack: 4, health: 2 })],
  BG25_009: [a("death", "summon", { id: "BG25_008" })],
  BG_TTN_401: [a("aura", "globalStats", { key: "automatonSummons", attack: 3, health: 2 })],
  BG32_172: [a("death", "summon", { id: "BG_TTN_401" })],
  BG35_342: [a("aura", "globalStats", { key: "deathrattles", attack: 4, health: 2 })],
  BGS_020: [a("battlecry", "murlocDiscover")],
  BGS_126: [a("aura", "overkillAdjacent")],
};
export const expandedSpells: Record<string, Ability[]> = {
  BG35_MagicItem_812t: [a("cast", "trinketPrize", { amount: 3 })],
  BG35_MagicItem_817t: [a("cast", "trinketCopy", { target: "selected", tier: 3 })],
  BG30_MagicItem_416t: [a("cast", "trinketEvolve", { target: "selected" })],
  BG35_MagicItem_755t: [a("cast", "battlecryShop")],
  BG35_MagicItem_306t: [a("cast", "trinketDestroyUndead", { target: "selected", tribe: "亡灵" })],
  BG35_MagicItem_733t: [a("cast", "trinketDestroyUndead", { target: "selected", tribe: "亡灵", amount: 2 })],
  BG35_MagicItem_872t: [a("cast", "buff", { target: "selected", tribe: "野兽", attack: 2, health: 2, keyword: "复生" })],
  BG27_514t: [a("cast", "copyShop", { target: "selected" })],
  BG36_MagicItem_208t: [a("cast", "deathrattle", { target: "selected" })],
  BG28_571: [a("cast", "gold", { amount: 1 }), a("aura", "healthCost")],
  BG28_573: [a("cast", "combatEffect", { key: "enemyOne" })],
  BG28_601: [a("cast", "murlocPair")],
  BG28_603: [a("cast", "combatEffect", { key: "beetles", amount: 2 })],
  BG28_604: [a("cast", "butchering", { target: "selected", tribe: "亡灵" })],
  BG28_606: [a("cast", "randomSpellcraft", { amount: 3 })],
  BG28_698: [a("cast", "confiscateGems", { target: "selected" })],
  BG28_849: [a("cast", "spellShop")],
  BG28_884: [a("cast", "combatEffect", { key: "confidence" })],
  BG30_804: [a("cast", "evolve", { target: "selected" })],
  BG31_880: [a("cast", "choose", { id: "BG31_880" })],
  BG31_881: [a("cast", "choose", { id: "BG31_881" })],
  BG31_886: [a("cast", "choose", { id: "BG31_886" })],
  BG31_890: [a("cast", "choose", { id: "BG31_890" })],
  BG31_892: [a("cast", "discoverChoice")],
  BG32_815: [a("cast", "nagaRepeatedBuff", { target: "selected" })],
  BG33_899: [a("cast", "sellTransfer", { target: "selected", key: "elemental" })],
  BG34_330: [a("cast", "lockedDiscover")],
  BG34_689: [a("cast", "scale", { key: "gemBarrage", attack: 1 })],
  BG34_888: [a("cast", "doomedDiscover")],
  BG34_889: [a("cast", "combatEffect", { key: "doubleLeft" })],
  BG35_912: [a("cast", "tribeShop", { target: "selected" })],
  BG36_883: [b("cast", 2, 3, "selected"), a("cast", "winnerBuff", { target: "selected" })],
  EBG_Spell_032: [a("cast", "sellTransfer", { target: "selected" })],
  EBG_Spell_038: [a("cast", "tribeRefresh", { target: "selected" })],
  BG27_084t: [a("cast", "buff", { attack: 1, health: 1, target: "selected", tribe: "野兽", keyword: "复生" })],
  BG27_084t2: [a("cast", "buff", { attack: 4, target: "selected", tribe: "野兽", keyword: "风怒" })],
  BG30_123t: [a("cast", "scale", { key: "gem", attack: 1, health: 1 })],
  BG30_123t2: [a("cast", "generate", { id: "BG20_GEM", amount: 4 })],
  BG31_320t: [a("cast", "generate", { id: "BG20_GEM", amount: 2 })],
  BG31_320t2: [a("cast", "scale", { key: "gem", attack: 1, health: 1 })],
  BG32_237t: [a("cast", "scale", { key: "spell", attack: 1 })],
  BG32_237t2: [a("cast", "scale", { key: "spell", health: 1 })],
  BG36_330t: [a("cast", "freeRefresh", { amount: 2 })],
  BG36_330t2: [a("cast", "generate", { id: "BG20_GEM", amount: 3 })],
  BG36_332t: [a("cast", "draw", { tribe: "野猪人" })],
  BG36_332t2: [a("cast", "goldCap")],
  BG36_341t: [a("cast", "gem", { target: "all", amount: 3 })],
  BG36_341t2: [a("cast", "castTavern", { id: "BG34_689", amount: 3 })],
  BG31_880t: [b("cast", 3, 1, "selected")], BG31_880t2: [b("cast", 1, 3, "selected")],
  BG31_881t: [b("cast", 2, 2, "all")],
  BG31_881t2: [a("cast", "delayedBuff", { attack: 2, health: 2, amount: 2 })],
  BG31_886t: [b("cast", 6, 6, "selected"), b("cast", 6, 6, "selected")],
  BG31_886t2: [b("cast", 2, 2, "all")],
  BG31_890t: [a("cast", "discoverSpell", { key: "currentTier" })],
  BG31_890t2: [a("cast", "discoverMinion", { key: "currentTier" })],
  BG31_893: [a("cast", "choose", { id: "BG31_326" })],
  BG31_326t: [a("cast", "scale", { key: "gem", attack: 1 })],
  BG31_326t2: [a("cast", "scale", { key: "gem", health: 1 })],
};
