import type { Ability, Tribe } from "../data";

export interface TrinketRule extends Ability {
  every?: number;
  limit?: number;
  perTurn?: boolean;
  combatOnly?: boolean;
  subjectTribe?: Tribe;
}
const r = (event: string, op: string, rest: Partial<TrinketRule> = {}): TrinketRule => ({ event, op, ...rest });
const grant = (id: string, amount = 1) => r("purchase", "generate", { id, amount });
const recurring = (id: string, amount = 1) => [grant(id, amount), r("start", "generate", { id, amount })];
const custom = (...events: string[]) => events.map((event) => r(event, "trinketCustom"));

// The event registry is also the implementation allowlist. Historical definitions
// stay in snapshot.json; pool membership is kept separate from executable effects.
export const returningTrinkets: Record<string, TrinketRule[]> = {
  BG30_MagicItem_431: [grant('BG28_707')],
  BG30_MagicItem_943: [grant('BG30_121')],
  BG32_MagicItem_892: custom('purchase', 'start'),
  BG32_MagicItem_925: [grant('BG31_148'), ...custom('end')],
  BG36_MagicItem_400: [grant('BG36_303', 2)],
  BG36_MagicItem_402: [grant('BG36_108')],
  BG36_MagicItem_403: [], BG36_MagicItem_403t: [],
  BG36_MagicItem_404: custom('tavernSpell'), BG36_MagicItem_404t: custom('tavernSpell'),
  BG36_MagicItem_406: custom('discard'),
  BG36_MagicItem_407: [r('attack', 'trinketCustom', { every: 13 })],
  BG36_MagicItem_408: [r('spend', 'trinketCustom', { every: 50 })],
  BG36_MagicItem_409: custom('cardPlayed'),
  BG36_MagicItem_410: [r('summon', 'trinketCustom', { every: 25 })],
  BG36_MagicItem_411: custom('purchase'),
  BG36_MagicItem_412: custom('purchase'), BG36_MagicItem_412t2: custom('purchase'),
  BG36_MagicItem_414: custom('end'), BG36_MagicItem_416: [],
  BG36_MagicItem_417: custom('purchase', 'start'),
  BG36_MagicItem_418: [r('discard', 'scale', { key: 'spell', attack: 1, health: 1, every: 3 })],
  BG36_MagicItem_423: custom('purchase', 'start'), BG36_MagicItem_423t: custom('purchase', 'start'),
  BG36_MagicItem_424: custom('purchase', 'start'),
  BG36_MagicItem_430: [grant('BG36_301t'), r('discard', 'generate', { id: 'BG36_301t' })],
  BG36_MagicItem_450: [grant('BG36_206', 2), ...custom('death')],
  BG36_MagicItem_600: [grant('BG36_318'), ...custom('combat')],
  BG36_MagicItem_602: custom('purchase'), BG36_MagicItem_606: custom('discard'),
  BG36_MagicItem_609: custom('buy', 'buySpell'),
  BG36_MagicItem_610: custom('purchase'), BG36_MagicItem_611: recurring('BG34_272'),
  BG36_MagicItem_852: custom('purchase', 'start'),

  BG30_MagicItem_301: [grant("BG25_008"), ...custom("combat")],
  BG30_MagicItem_303: custom("combat"),
  BG30_MagicItem_310: [grant("BG25_354"), ...custom("combat")],
  BG30_MagicItem_403: custom("combat"),
  BG30_MagicItem_406: recurring("BG28_604"),
  BG30_MagicItem_410: [r("death", "scale", { key: "gem", health: 1, every: 3, combatOnly: true })],
  BG30_MagicItem_410t2: [r("death", "scale", { key: "gem", attack: 1, health: 1, every: 4, combatOnly: true })],
  BG30_MagicItem_411: custom("combat"),
  BG30_MagicItem_416: custom("purchase", "start"),
  BG30_MagicItem_418: [grant("BG_LOE_077"), r("purchase", "trinketDraw", { key: "BATTLECRY" }), ...custom("sync")],
  BG30_MagicItem_420: [r("purchase", "discoverSpell"), r("start", "discoverSpell")],
  BG30_MagicItem_420t: [r("purchase", "discoverSpell", { amount: 2 }), r("start", "discoverSpell", { amount: 2 })],
  BG30_MagicItem_422: [r("targetSpell", "buff", { target: "selected", attack: 4, health: 4 })],
  BG30_MagicItem_422t: [r("targetSpell", "buff", { target: "selected", attack: 10, health: 10 })],
  BG30_MagicItem_423: custom("refresh"),
  BG30_MagicItem_425: [r("start", "trinketCustom", { every: 2 })],
  BG30_MagicItem_426: custom("purchase", "start"),
  BG30_MagicItem_426t: custom("purchase", "start"),
  BG30_MagicItem_430: [r("purchase", "trinketDraw", { key: "BATTLECRY" }), r("start", "trinketDraw", { key: "BATTLECRY" })],
  BG30_MagicItem_434: custom("aura"),
  BG30_MagicItem_435: [r("end", "generate", { id: "BG26_813t", every: 3 })],
  BG30_MagicItem_437: [r("death", "buff", { target: "random", tribe: "亡灵", keyword: "复生", every: 5, combatOnly: true })],
  BG30_MagicItem_439: custom("aura"),
  BG30_MagicItem_442: [r("death", "trinketCustom", { subjectTribe: "野猪人", combatOnly: true })],
  BG30_MagicItem_540: [r("summon", "doubleAttack", { target: "event", subjectTribe: "野兽", combatOnly: true })],
  BG30_MagicItem_541: [r("purchase", "scale", { key: "shop", attack: 2, health: 2 }), r("heroDamage", "scale", { key: "shop", attack: 2, health: 2, every: 3 })],
  BG30_MagicItem_544: [r("play", "scale", { subjectTribe: "元素", key: "elementalShop", attack: 3, health: 2 })],
  BG30_MagicItem_544t: [r("play", "scale", { subjectTribe: "元素", key: "elementalShop", attack: 5, health: 5 })],
  BG30_MagicItem_545: [r("death", "draw", { magnetic: true, every: 3, combatOnly: true })],
  BG30_MagicItem_546: [r("attack", "gem", { target: "all", tribe: "野猪人", every: 2, combatOnly: true })],
  BG30_MagicItem_547: [r("tavernSpell", "scale", { key: "undead", attack: 1 })],
  BG30_MagicItem_547t: [r("tavernSpell", "scale", { key: "undead", attack: 2 })],
  BG30_MagicItem_700: [r("purchase", "discoverMinion", { key: "DEATHRATTLE" }), ...custom("aura")],
  BG30_MagicItem_701: custom("aura"),
  BG30_MagicItem_703: custom("purchase", "start"),
  BG30_MagicItem_705: custom("purchase", "start"),
  BG30_MagicItem_706: custom("purchase", "start"),
  BG30_MagicItem_707: custom("purchase", "start"),
  BG30_MagicItem_713: [r("death", "draw", { tribe: "亡灵", every: 8 })],
  BG30_MagicItem_801: custom("discover"),
  BG30_MagicItem_804: custom("aura"),
  BG30_MagicItem_821: [grant("TB_BaconShop_HP_105t")],
  BG30_MagicItem_841: [r("purchase", "scale", { key: "shop", attack: 3, health: 3 }), ...custom("aura")],
  BG30_MagicItem_847: [r("end", "goldCap")],
  BG30_MagicItem_868: [grant("BG26_174"), grant("BGS_004"), ...custom("aura")],
  BG30_MagicItem_876: [grant("BG_EX1_564")],
  BG30_MagicItem_879t: [r("purchase", "scale", { key: "shop", attack: 2, health: 2 }), r("refresh", "scale", { key: "shop", attack: 2, health: 2, every: 4 })],
  BG30_MagicItem_886: [r("summon", "buff", { target: "event", keyword: "圣盾", limit: 5, combatOnly: true })],
  BG30_MagicItem_888: custom("aura"),
  BG30_MagicItem_891: custom("start"),
  BG30_MagicItem_900: [r("cardPlayed", "buff", { target: "random", tribe: "龙", attack: 4, health: 4 })],
  BG30_MagicItem_902: custom("combat"),
  BG30_MagicItem_914: [r("play", "buff", { target: "handLeft", attack: 3, health: 3 })],
  BG30_MagicItem_914t: [r("play", "buff", { target: "handLeft", attack: 6, health: 6 })],
  BG30_MagicItem_917: custom("combat"),
  BG30_MagicItem_919: [r("play", "randomSpellcraft", { subjectTribe: "纳迦", every: 2 })],
  BG30_MagicItem_920: [grant("BG28_606"), ...custom("aura")],
  BG30_MagicItem_924: custom("spend"),
  BG30_MagicItem_924t: custom("spend"),
  BG30_MagicItem_931: [r("death", "draw", { tribe: "野兽", every: 7 })],
  BG30_MagicItem_942: custom("purchase", "start"),
  BG30_MagicItem_951: [r("sell", "draw", { tribe: "元素", every: 7 })],
  BG30_MagicItem_952: custom("combat"),
  BG30_MagicItem_962: custom("combat"),
  BG30_MagicItem_973: custom("refresh"),
  BG30_MagicItem_981: custom("death"),
  BG30_MagicItem_988: [grant("BG20_GEM", 3), r("purchase", "scale", { key: "gem", attack: 2, health: 1 })],
  BG30_MagicItem_988t: [grant("BG20_GEM", 5), r("purchase", "scale", { key: "gem", attack: 3, health: 3 })],
  BG30_MagicItem_989t: [r("purchase", "scale", { key: "undead", attack: 15 })],
  BG30_MagicItem_993: custom("purchase", "start"),
  BG30_MagicItem_994: custom("purchase", "start"),
  BG30_MagicItem_995: custom("combat"),
  BG30_MagicItem_996: [r("purchase", "goldCap", { amount: 4 }), r("purchase", "gold", { amount: 4 })],
  BG30_MagicItem_998: [r("purchase", "gold", { amount: 2 }), ...custom("aura")],
  BG30_MagicItem_999: [r("spend", "castTavern", { id: "BG28_168", every: 7 })],
  BG31_MagicItem_903: recurring("BG30_802"),
  BG32_MagicItem_170: custom("play"),
  BG32_MagicItem_172: recurring("BG31_176"),
  BG32_MagicItem_200: custom("attack"),
  BG32_MagicItem_205: [grant("BG32_340"), r("destroy", "gold", { amount: 2 })],
  BG32_MagicItem_232: [r("spend", "trinketCustom", { every: 10 })],
  BG32_MagicItem_270t: [r("death", "scale", { key: "spell", attack: 1, health: 1, every: 4, combatOnly: true })],
  BG32_MagicItem_271: [r("purchase", "gold", { amount: 2 }), ...custom("purchase", "start")],
  BG32_MagicItem_276: [r("end", "scale", { key: "undead", attack: 2 })],
  BG32_MagicItem_278: [r("buy", "trinketCustom", { limit: 1, perTurn: true })],
  BG32_MagicItem_283: [grant("BG28_741"), ...custom("aura")],
  BG32_MagicItem_284: [r("end", "gem", { target: "menagerie", amount: 7 })],
  BG32_MagicItem_300: custom("purchase", "start"),
  BG32_MagicItem_301: [grant("BG26_350"), r("summon", "buff", { subjectTribe: "鱼人", target: "event", keyword: "圣盾", combatOnly: true })],
  BG32_MagicItem_306: custom("combat"),
  BG32_MagicItem_350: custom("sync"),
  BG32_MagicItem_360: custom("combat"),
  BG32_MagicItem_361: custom("purchase", "start"),
  BG32_MagicItem_361t: custom("purchase", "start"),
  BG32_MagicItem_362t: custom("purchase"),
  BG32_MagicItem_363: [r("attack", "buff", { subjectTribe: "龙", target: "event", keyword: "圣盾", limit: 3, combatOnly: true })],
  BG32_MagicItem_364: [grant("BG34_Giant_314")],
  BG32_MagicItem_366: custom("aura"),
  BG32_MagicItem_367: custom("aura"),
  BG32_MagicItem_400: custom("purchase"),
  BG32_MagicItem_416: custom("aura"),
  BG32_MagicItem_428: custom("start"),
  BG32_MagicItem_801t: custom("aura"),
  BG32_MagicItem_807: custom("purchase"),
  BG32_MagicItem_808: [r("spell", "gem", { target: "all", every: 4 })],
  BG32_MagicItem_808t: [r("spell", "gem", { target: "all", amount: 2, every: 5 })],
  BG32_MagicItem_817: custom("purchase", "end"),
  BG32_MagicItem_821: custom("aura"),
  BG32_MagicItem_822: custom("aura"),
  BG32_MagicItem_831: recurring("BGS_115"),
  BG32_MagicItem_858: [r("purchase", "draw", { tier: 4, amount: 3 })],
  BG32_MagicItem_860: [r("death", "trinketCustom", { every: 5, combatOnly: true })],
  BG32_MagicItem_860t: [r("death", "trinketCustom", { every: 7, combatOnly: true })],
  BG32_MagicItem_888: [r("play", "freeRefresh", { subjectTribe: "元素" })],
  BG32_MagicItem_893: [r("tavernSpell", "buff", { target: "left", attack: 3, health: 3 }), r("tavernSpell", "buff", { target: "handLeft", attack: 3, health: 3 })],
  BG32_MagicItem_901: [r("purchase", "freeRefresh", { amount: 5 }), ...custom("buy")],
  BG32_MagicItem_920: [grant("BG31_924", 2), ...custom("aura")],
  BG32_MagicItem_922: custom("spell", "end"),
  BG32_MagicItem_926: [grant("BG27_513")],
  BG32_MagicItem_930: [r("spell", "draw", { tribe: "纳迦", every: 8 })],
  BG32_MagicItem_931: [r("purchase", "randomSpellcraft", { amount: 3 }), r("start", "randomSpellcraft", { amount: 3 })],
  BG32_MagicItem_951: custom("purchase", "start"),
  BG32_MagicItem_957: [grant("BG31_826"), ...custom("aura")],
  BG32_MagicItem_998: [grant("BG31_360")],
  BG35_MagicItem_150: custom("refresh"),
  BG35_MagicItem_151: [grant("BG35_151"), ...custom("aura")],
  BG35_MagicItem_151t: [grant("BG35_151"), ...custom("aura")],
  BG35_MagicItem_152: [r("refresh", "trinketCustom", { every: 4 })],
  BG35_MagicItem_154: custom("play"),
  BG35_MagicItem_156: [grant("BG34_500"), ...custom("aura")],
  BG35_MagicItem_301: [r("purchase", "draw", { tribe: "机械", magnetic: true }), r("start", "draw", { tribe: "机械", magnetic: true })],
  BG35_MagicItem_302: [r("death", "draw", { tribe: "机械", every: 6 })],
  BG35_MagicItem_305: [grant("BG28_601"), r("start", "generate", { id: "BG28_601", every: 2 })],
  BG35_MagicItem_309: custom("purchase", "start"),
  BG35_MagicItem_306: custom("purchase", "start"),
  BG35_MagicItem_434: custom("purchase", "start"),
  BG35_MagicItem_700: [r("summon", "draw", { subjectTribe: "野兽", tribe: "野兽", every: 6 })],
  BG35_MagicItem_701: custom("combat", "summon"),
  BG35_MagicItem_710: [r("tavernSpell", "buff", { target: "all", tribe: "海盗", attack: 3, health: 3 })],
  BG35_MagicItem_711: [r("combat", "buff", { target: "randomFour", tribe: "海盗", keyword: "圣盾" })],
  BG35_MagicItem_712: [grant("BG33_825"), r("purchase", "bounty", { amount: 2 }), r("start", "bounty", { amount: 2 })],
  BG35_MagicItem_713: [r("acquire", "buff", { subjectTribe: "海盗", target: "left", attack: 16, health: 16 })],
  BG35_MagicItem_732: custom("combat", "empty"),
  BG35_MagicItem_733: custom("purchase", "start"),
  BG35_MagicItem_740: [grant("BG35_342"), ...custom("combat")],
  BG35_MagicItem_741: [grant("BG26_149")],
  BG35_MagicItem_742: custom("end"),
  BG35_MagicItem_743: custom("refresh", "aura"),
  BG35_MagicItem_750: [r("buySpell", "learnSpell", { limit: 2, perTurn: true })],
  BG35_MagicItem_752: custom("end"),
  BG35_MagicItem_754: custom("combat"),
  BG35_MagicItem_755: custom("purchase", "start"),
  BG35_MagicItem_801: [r("heroPower", "gold"), ...custom("aura")],
  BG35_MagicItem_812: custom("purchase", "aura"),
  BG35_MagicItem_814: custom("upgrade"),
  BG35_MagicItem_815: [r("purchase", "draw", { tier: 1, amount: 2 }), r("purchase", "draw", { tier: 2, amount: 2 }), r("purchase", "draw", { tier: 3, amount: 2 })],
  BG35_MagicItem_816: custom("purchase"),
  BG35_MagicItem_816t: custom("purchase"),
  BG35_MagicItem_817: [grant("BG35_MagicItem_817t"), r("start", "generate", { id: "BG35_MagicItem_817t", every: 2 })],
  BG35_MagicItem_818: [r("purchase", "gold", { amount: 10 }), ...custom("aura")],
  BG35_MagicItem_820: [r("purchase", "gold", { amount: 5 }), ...custom("purchase")],
  BG35_MagicItem_821: custom("purchase"),
  BG35_MagicItem_821t: custom("purchase"),
  BG35_MagicItem_823: custom("purchase"),
  BG35_MagicItem_823t: custom("purchase"),
  BG35_MagicItem_840: [r("purchase", "chromadrake"), r("start", "chromadrake")],
  BG35_MagicItem_840t: [r("purchase", "chromadrake", { amount: 2 }), r("battlecryPlayed", "chromadrake", { amount: 2, every: 7 })],
  BG35_MagicItem_850: [r("purchase", "castTavern", { id: "BG34_444" }), r("start", "castTavern", { id: "BG34_444" })],
  BG35_MagicItem_850t: [r("purchase", "castTavern", { id: "BG34_444", amount: 4 }), r("start", "castTavern", { id: "BG34_444", amount: 2 })],
  BG35_MagicItem_851: [r("play", "randomSpell", { subjectTribe: "元素", limit: 2, perTurn: true })],
  BG35_MagicItem_861: [grant("BG31_819"), r("play", "generate", { subjectTribe: "元素", id: "BG31_819", every: 11 })],
  BG35_MagicItem_862: custom("refresh"),
  BG35_MagicItem_863: [grant("BG33_899"), r("sell", "generate", { id: "BG33_899", every: 4 })],
  BG35_MagicItem_871: [r("summon", "buff", { subjectTribe: "野兽", target: "event", attack: 6, health: 6 })],
  BG35_MagicItem_872: custom("purchase", "start"),
  BG35_MagicItem_890: [r("purchase", "bounty", { amount: 2 }), r("start", "bounty", { amount: 2 })],
  BG35_MagicItem_920: [r("spell", "scale", { key: "spell", attack: 4, health: 4, every: 14, limit: 14 })],
  BG35_MagicItem_923: custom("spell"),
  BG35_MagicItem_924: [grant("BG31_035"), ...custom("aura")],
  BG35_MagicItem_930: [r("purchase", "freeRefresh"), ...custom("purchase")],
  BG35_MagicItem_931: [r("buy", "trinketCustom", { limit: 2 })],
  BG35_MagicItem_931t: [r("buy", "trinketCustom", { limit: 4 })],
};
